CUDNN_BENCHMARK: false
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  SAMPLE_PER_CLASS: -1
  SAMPLE_SEED: 0
  TEST:
  - coco_2way_cls0_1
  - coco_2way_cls0_2
  - coco_2way_cls0_3
  - coco_2way_cls0_4
  - coco_2way_cls0_5
  - coco_2way_cls0_6
  - coco_2way_cls0_7
  - coco_2way_cls0_8
  - coco_2way_cls0_9
  - coco_2way_cls0_10
  - coco_2way_cls0_11
  - coco_2way_cls0_12
  - coco_2way_cls0_13
  - coco_2way_cls0_14
  - coco_2way_cls0_15
  - coco_2way_cls0_16
  - coco_2way_cls0_17
  - coco_2way_cls0_18
  - coco_2way_cls0_19
  - coco_2way_cls1_2
  - coco_2way_cls1_3
  - coco_2way_cls1_5
  - coco_2way_cls1_6
  - coco_2way_cls1_7
  - coco_2way_cls1_8
  - coco_2way_cls1_9
  - coco_2way_cls1_10
  - coco_2way_cls1_11
  - coco_2way_cls1_12
  - coco_2way_cls1_13
  - coco_2way_cls1_14
  - coco_2way_cls1_15
  - coco_2way_cls1_16
  - coco_2way_cls1_17
  - coco_2way_cls1_18
  - coco_2way_cls1_19
  - coco_2way_cls2_3
  - coco_2way_cls2_4
  - coco_2way_cls2_5
  - coco_2way_cls2_6
  - coco_2way_cls2_7
  - coco_2way_cls2_8
  - coco_2way_cls2_9
  - coco_2way_cls2_10
  - coco_2way_cls2_11
  - coco_2way_cls2_12
  - coco_2way_cls2_13
  - coco_2way_cls2_14
  - coco_2way_cls2_15
  - coco_2way_cls2_16
  - coco_2way_cls2_17
  - coco_2way_cls2_18
  - coco_2way_cls2_19
  - coco_2way_cls3_4
  - coco_2way_cls3_5
  - coco_2way_cls3_6
  - coco_2way_cls3_7
  - coco_2way_cls3_8
  - coco_2way_cls3_9
  - coco_2way_cls3_10
  - coco_2way_cls3_11
  - coco_2way_cls3_12
  - coco_2way_cls3_13
  - coco_2way_cls3_14
  - coco_2way_cls3_15
  - coco_2way_cls3_16
  - coco_2way_cls3_17
  - coco_2way_cls3_18
  - coco_2way_cls3_19
  - coco_2way_cls4_5
  - coco_2way_cls4_6
  - coco_2way_cls4_7
  - coco_2way_cls4_8
  - coco_2way_cls4_12
  - coco_2way_cls4_13
  - coco_2way_cls4_14
  - coco_2way_cls4_16
  - coco_2way_cls4_19
  - coco_2way_cls5_6
  - coco_2way_cls5_7
  - coco_2way_cls5_8
  - coco_2way_cls5_9
  - coco_2way_cls5_10
  - coco_2way_cls5_11
  - coco_2way_cls5_12
  - coco_2way_cls5_13
  - coco_2way_cls5_16
  - coco_2way_cls5_17
  - coco_2way_cls5_18
  - coco_2way_cls5_19
  - coco_2way_cls6_7
  - coco_2way_cls6_8
  - coco_2way_cls6_9
  - coco_2way_cls6_10
  - coco_2way_cls6_11
  - coco_2way_cls6_12
  - coco_2way_cls6_13
  - coco_2way_cls6_16
  - coco_2way_cls6_17
  - coco_2way_cls6_18
  - coco_2way_cls6_19
  - coco_2way_cls7_8
  - coco_2way_cls7_9
  - coco_2way_cls7_10
  - coco_2way_cls7_11
  - coco_2way_cls7_12
  - coco_2way_cls7_13
  - coco_2way_cls7_14
  - coco_2way_cls7_15
  - coco_2way_cls7_16
  - coco_2way_cls7_17
  - coco_2way_cls7_18
  - coco_2way_cls7_19
  - coco_2way_cls8_10
  - coco_2way_cls8_13
  - coco_2way_cls8_14
  - coco_2way_cls8_15
  - coco_2way_cls8_16
  - coco_2way_cls8_17
  - coco_2way_cls8_18
  - coco_2way_cls8_19
  - coco_2way_cls9_10
  - coco_2way_cls9_11
  - coco_2way_cls9_12
  - coco_2way_cls9_16
  - coco_2way_cls9_17
  - coco_2way_cls10_11
  - coco_2way_cls10_13
  - coco_2way_cls10_14
  - coco_2way_cls10_15
  - coco_2way_cls10_16
  - coco_2way_cls10_19
  - coco_2way_cls11_12
  - coco_2way_cls11_15
  - coco_2way_cls11_16
  - coco_2way_cls12_13
  - coco_2way_cls12_16
  - coco_2way_cls12_17
  - coco_2way_cls13_14
  - coco_2way_cls13_15
  - coco_2way_cls13_16
  - coco_2way_cls13_17
  - coco_2way_cls13_18
  - coco_2way_cls13_19
  - coco_2way_cls14_15
  - coco_2way_cls14_16
  - coco_2way_cls14_17
  - coco_2way_cls14_18
  - coco_2way_cls14_19
  - coco_2way_cls15_16
  - coco_2way_cls15_17
  - coco_2way_cls15_18
  - coco_2way_cls16_17
  - coco_2way_cls16_18
  - coco_2way_cls16_19
  - coco_2way_cls17_18
  - coco_2way_cls17_19
  - coco_2way_cls18_19
  TRAIN:
  - coco14_base_sem_seg_fold0
  SAL_ROOT: ./datasets/COCO14/Sal_val
  VIS_MULTIPLIER: 127
GLOBAL:
  HACK: 1.0
INPUT:
  COLOR_AUG_SSD: true
  CROP:
    ENABLED: true
    SINGLE_CATEGORY_MAX_AREA: 1.0
    SIZE:
    - 640
    - 640
    TYPE: absolute
  DATASET_MAPPER_NAME: mask_former_semantic
  FORMAT: RGB
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 2560
  MAX_SIZE_TRAIN: 2560
  MIN_SIZE_TEST: 640
  MIN_SIZE_TRAIN:
  - 320
  - 384
  - 448
  - 512
  - 576
  - 640
  - 704
  - 768
  - 832
  - 896
  - 960
  MIN_SIZE_TRAIN_SAMPLING: choice
  RANDOM_FLIP: horizontal
  SIZE_DIVISIBILITY: 640
MODEL:
  ANCHOR_GENERATOR:
    ANGLES:
    - - -90
      - 0
      - 90
    ASPECT_RATIOS:
    - - 0.5
      - 1.0
      - 2.0
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES:
    - - 32
      - 64
      - 128
      - 256
      - 512
  BACKBONE:
    FREEZE_AT: 0
    NAME: build_resnet_deeplab_backbone
  CLIP_ADAPTER:
    INSTANCE_WEIGHT: 0.01
    CLIP_ENSEMBLE: true
    CLIP_ENSEMBLE_WEIGHT: 0.7
    CLIP_MODEL_NAME: ViT-B/16
    MASK_EXPAND_RATIO: 1.0
    MASK_FILL: mean
    MASK_MATTING: false
    MASK_THR: 0.5
    PREDEFINED_PROMPT_TEMPLATES:
    - a sculpture of a {}.
    PROMPT_DIM: 512
    PROMPT_LEARNER: instance_learnable
    PROMPT_CHECKPOINT: ./output_coco/learn_instance/fold0/model_final.pth
    PROMPT_SHAPE:
    - 16
    - 0
    REGION_CLIP_ADAPTER:
      CLIP_MODEL_NAME: ViT-B/16
      PREDEFINED_PROMPT_TEMPLATES:
      - a sculpture of a {}.
      PROMPT_CHECKPOINT: ./output_coco/learn_instance/fold0/model_final.pth
      PROMPT_DIM: 512
      PROMPT_LEARNER: instance_learnable
      PROMPT_SHAPE:
      - 16
      - 0
    REGION_RESIZED: true
    SEPERATE_ADAPTER: false
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES: []
    NORM: ''
    OUT_CHANNELS: 256
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  MASK_FORMER:
    DEC_LAYERS: 6
    DEEP_SUPERVISION: true
    DICE_WEIGHT: 1.0
    DIM_FEEDFORWARD: 2048
    DROPOUT: 0.1
    ENC_LAYERS: 0
    ENFORCE_INPUT_PROJ: false
    HIDDEN_DIM: 256
    MASK_WEIGHT: 20.0
    NHEADS: 8
    NO_OBJECT_WEIGHT: 0.1
    NUM_OBJECT_QUERIES: 100
    PRE_NORM: false
    SIZE_DIVISIBILITY: 32
    TEST:
      OBJECT_MASK_THRESHOLD: 0.0
      OVERLAP_THRESHOLD: 0.0
      PANOPTIC_ON: false
      SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: false
    TRANSFORMER_IN_FEATURE: res5
  MASK_ON: false
  META_ARCHITECTURE: ZeroShotMaskFormer
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: true
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.12
  - 57.375
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    DEFORM_MODULATED: false
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE:
    - false
    - false
    - false
    - false
    DEPTH: 50
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    RES2_OUT_CHANNELS: 256
    RES4_DILATION: 1
    RES5_DILATION: 1
    RES5_MULTI_GRID:
    - 1
    - 2
    - 4
    STEM_OUT_CHANNELS: 128
    STEM_TYPE: deeplab
    STRIDE_IN_1X1: false
    WIDTH_PER_GROUP: 64
  RETINANET:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES:
    - p3
    - p4
    - p5
    - p6
    - p7
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.4
    - 0.5
    NMS_THRESH_TEST: 0.5
    NORM: ''
    NUM_CLASSES: 60
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 1000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS:
    - - 10.0
      - 10.0
      - 5.0
      - 5.0
    - - 20.0
      - 20.0
      - 10.0
      - 10.0
    - - 30.0
      - 30.0
      - 15.0
      - 15.0
    IOUS:
    - 0.5
    - 0.6
    - 0.7
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    BOUNDARY_THRESH: -1
    CONV_DIMS:
    - -1
    HEAD_NAME: StandardRPNHead
    IN_FEATURES:
    - res4
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.3
    - 0.7
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 6000
    PRE_NMS_TOPK_TRAIN: 12000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    ASPP_CHANNELS: 256
    ASPP_DILATIONS:
    - 6
    - 12
    - 18
    ASPP_DROPOUT: 0.1
    COMMON_STRIDE: 4
    CONVS_DIM: 256
    EMBEDDING_DIM: 512
    EMBED_HIDDEN_DIM: 1024
    EMBED_LAYERS: 2
    IGNORE_VALUE: 255
    IN_FEATURES:
    - res2
    - res3
    - res4
    - res5
    LOSS_TYPE: hard_pixel_mining
    LOSS_WEIGHT: 1.0
    MASK_DIM: 256
    NAME: ZeroShotMaskFormerHead
    NORM: GN
    NUM_CLASSES: 60
    PIXEL_DECODER_NAME: BasePixelDecoder
    PROJECT_CHANNELS:
    - 48
    PROJECT_FEATURES:
    - res2
    TRANSFORMER_ENC_LAYERS: 0
    USE_DEPTHWISE_SEPARABLE_CONV: false
  SWIN:
    APE: false
    ATTN_DROP_RATE: 0.0
    DEPTHS:
    - 2
    - 2
    - 6
    - 2
    DROP_PATH_RATE: 0.3
    DROP_RATE: 0.0
    EMBED_DIM: 96
    MLP_RATIO: 4.0
    NUM_HEADS:
    - 3
    - 6
    - 12
    - 24
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    PATCH_NORM: true
    PATCH_SIZE: 4
    PRETRAIN_IMG_SIZE: 224
    QKV_BIAS: true
    QK_SCALE: null
    WINDOW_SIZE: 7
  WEIGHTS: /home/iitd/prashant/WeakLSS/zsseg.baseline/output_coco/wzss/fold0/model_final.pth
ORACLE: false
OUTPUT_DIR: ./output_coco/wfss_2way/fold0
PSEUDO: false
PSEUDO_FLAG_NAME: trainable_flag
PSEUDO_REJECT_THRESHOLD: 0.0
PSEUDO_WITH_PRIOR: true
SEED: -1
SOLVER:
  AMP:
    ENABLED: false
  BACKBONE_MULTIPLIER: 0.1
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    CLIP_TYPE: full_model
    CLIP_VALUE: 0.01
    ENABLED: true
    NORM_TYPE: 2.0
  GAMMA: 0.1
  IMS_PER_BATCH: 30
  LR_SCHEDULER_NAME: WarmupPolyLR
  MAX_ITER: 60000
  MOMENTUM: 0.9
  NESTEROV: false
  OPTIMIZER: ADAMW
  POLY_LR_CONSTANT_ENDING: 0.0
  POLY_LR_POWER: 0.9
  REFERENCE_WORLD_SIZE: 0
  STEPS:
  - 30000
  TEST_IMS_PER_BATCH: 1
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: null
  WEIGHT_DECAY_EMBED: 0.0
  WEIGHT_DECAY_NORM: 0.0
TEST:
  AUG:
    ENABLED: false
    FLIP: true
    MAX_SIZE: 4480
    MIN_SIZES:
    - 320
    - 480
    - 640
    - 800
    - 960
    - 1120
  DENSE_CRF: false
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 20000
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: false
    NUM_ITER: 200
  SLIDING_OVERLAP: 0.6666666666666666
  SLIDING_TILE_SIZE: 224
  SLIDING_WINDOW: false
VERSION: 2
VIS_PERIOD: 0
WANDB:
  NAME: null
  PROJECT: zero_shot_seg
